language: go

go:
  - 1.12.x

sudo: false
before_script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go test ./...
  - go test -race ./...
  - golangci-lint run -E gocyclo -E errcheck -E prealloc -E gosec -E golint ./...
